baseURL = "https://chende.ren"
languageCode = "zh-CN"
title = "闪电侠的小黑板"
theme = "maupassant"

[author]
    name = "闪电侠"
[params]
    author = "闪电侠"
    subtitle = "专注于C、Node.js、Golang、Dart、WEB开发框架、高性能高可用架构、团队管理"
    keywords = "闪电侠,闪电侠的小黑板,C,C++,Go,C#,.NET,Python,Ruby,Node.js,Flutter,Dart,Golang,博客,部门管理,软件架构,Web框架,高可用,高性能"
    description = "IT技术，包括但不限于Go语言(golang)、C/C++、Flutter、Dart、Python、Node.js、项目管理、软件架构等"

[params.cc]
    name = "开放的「署名 4.0 国际 (CC BY 4.0)」创作共享协议"
    link = "https://creativecommons.org/licenses/by/4.0/deed.zh"



